apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arminssi/ai-model-platform.git
    targetRevision: main
    path: helm/model-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-models
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true